# Generated by Django 5.2.6 on 2025-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_login_link_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='custom_nav_items',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of page slugs to display when this page renders (leave empty to hide the navigation bar).'),
        ),
    ]
