# Generated by Django 5.2.6 on 2025-11-18 16:54

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_use_model_utils_timestamp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
    ]
