# Generated by Django 5.2.5 on 2025-09-01 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('emoji', models.CharField(blank=True, help_text="Optional short emoji label (e.g. '🍺')", max_length=8)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="e.g. 'phone', 'address', 'age'", max_length=100)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admins only'), ('STAFF_ONLY', 'Staff users'), ('AUTHENTICATED', 'All logged-in users'), ('PUBLIC', 'Public/Anyone')], default='AUTHENTICATED', max_length=20)),
            ],
            options={
                'unique_together': {('field_name',)},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('chosen_name', models.CharField(blank=True, max_length=200)),
                ('pronouns', models.CharField(blank=True, help_text='e.g. she/her, he/him, they/them', max_length=64)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('role_title', models.CharField(blank=True, help_text="Free-text role label, e.g. 'Bar lead'", max_length=120)),
                ('duties', models.TextField(blank=True)),
                ('force_password_change', models.BooleanField(default=True)),
                ('has_selected_visibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='users.badgedefinition')),
                ('primary_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
