# Generated by Django 5.2.5 on 2025-09-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgedefinition',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldpolicy',
            name='field_name',
            field=models.CharField(help_text="e.g. 'phone', 'address', 'birth_date', 'email', 'role_title'", max_length=100),
        ),
    ]
