# Generated by Django 5.2.5 on 2025-09-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_badgedefinition_options_remove_userprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1000, help_text='Lower = higher priority')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='auth.group')),
            ],
            options={
                'ordering': ['rank', 'group__name'],
            },
        ),
    ]
