# Generated by Django 5.2.5 on 2025-09-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupmeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldpolicy',
            options={'verbose_name_plural': 'field policies'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'permissions': (('can_impersonate', 'Can impersonate other users'),)},
        ),
        migrations.AlterUniqueTogether(
            name='fieldpolicy',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fieldpolicy',
            name='field_name',
            field=models.CharField(help_text="e.g. 'phone', 'address', 'birth_date', 'email', 'role_title'", max_length=100, unique=True),
        ),
    ]
