# Generated by Django 5.2.6 on 2025-10-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_reference', models.CharField(choices=[('event_start', 'Event start'), ('doors', 'Doors open')], default='event_start', help_text='Base time used to calculate the shift start.', max_length=20)),
                ('start_offset_minutes', models.IntegerField(default=0, help_text='Minutes relative to event start (negative = before).')),
                ('duration_minutes', models.PositiveIntegerField(default=180, help_text='Default length of the shift in minutes.')),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('allow_signup', models.BooleanField(default=True)),
                ('visibility_key', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_shifts', to='shifts.shifttemplate'),
        ),
    ]
