# Generated by Django 5.2.6 on 2025-10-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shifttemplate_shift_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='template_segment',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
