# Generated by Django 5.2.6 on 2025-10-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shift_template_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='start_reference',
            field=models.CharField(choices=[('event_start', 'Event start'), ('doors', 'Doors open')], default='doors', help_text='Base time used to calculate the shift start.', max_length=20),
        ),
    ]
