# Generated by Django 5.2.6 on 2025-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_venue_timezone'),
        ('shifts', '0004_alter_shifttemplate_start_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='template_staff_position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='end_offset_minutes',
            field=models.IntegerField(default=0, help_text='Minutes to subtract from the closing time (positive = earlier).'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='segment_count',
            field=models.PositiveIntegerField(default=1, help_text='How many sequential segments to split the coverage into.'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of people required in each segment.', verbose_name='People per segment'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Optional fixed duration per segment (0 = auto evenly split).'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='start_offset_minutes',
            field=models.IntegerField(default=0, help_text='Minutes relative to the chosen reference (negative = before).'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('event', 'template', 'template_segment', 'template_staff_position')},
        ),
    ]
