# Generated by Django 5.2.6 on 2025-10-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_type_event_recurrence_day_of_month_and_more'),
        ('shifts', '0005_shift_template_staff_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('event', 'template', 'template_segment', 'template_staff_position', 'start_at')},
        ),
    ]
