# Generated by Django 5.2.5 on 2025-09-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('VENUE', 'Venue / Club'), ('BAND', 'Band / Artist'), ('PERSON', 'Person / Blog')], default='VENUE', max_length=10)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('address_street', models.CharField(blank=True, max_length=200)),
                ('address_number', models.CharField(blank=True, max_length=20)),
                ('address_postal_code', models.CharField(blank=True, max_length=20)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('address_country', models.CharField(blank=True, max_length=120)),
                ('membership_enabled', models.BooleanField(default=False, help_text='Enable membership UI across the CMS')),
                ('membership_currency', models.CharField(default='CHF', max_length=8)),
                ('required_pages', models.TextField(blank=True, help_text='One page title per line (created if app.pages.Page exists).')),
                ('required_roles', models.TextField(blank=True, help_text='One role (Group) name per line (created if missing).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0)),
                ('closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='setup.sitesettings')),
            ],
            options={
                'unique_together': {('settings', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('months', models.PositiveIntegerField(default=12)),
                ('price_minor', models.PositiveIntegerField(default=0, help_text='In minor units (e.g. cents/rappen)')),
                ('active', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='setup.sitesettings')),
            ],
            options={
                'unique_together': {('settings', 'name')},
            },
        ),
    ]
