# Generated by Django 5.2.5 on 2025-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='membership_currency',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='required_roles',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_autocomplete',
            field=models.BooleanField(default=False, help_text='Enable address autocomplete (requires JS integration).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='EUR', help_text='Currency code (suggested list + free text)', max_length=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='geo_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_hint',
            field=models.CharField(blank=True, help_text='Short label shown next to money icon.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g., $, $$, $$$', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='same_as',
            field=models.TextField(blank=True, help_text='schema.org sameAs: one URL per line'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_bandcamp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_mastodon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_soundcloud',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_spotify',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='X / Twitter URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='membership_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VisibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Identifier to reference in templates, e.g. 'users.membership.block'", max_length=120, unique=True)),
                ('label', models.CharField(blank=True, help_text='Human-friendly name; editable.', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
    ]
