# Generated by Django 5.2.5 on 2025-09-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_remove_sitesettings_membership_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='acc_accessible_wc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acc_hearing_loop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acc_service_animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acc_step_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acc_visual_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acc_wheelchair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accessibility_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='awareness_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='awareness_contact_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='awareness_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='awareness_contact_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maximum_attendee_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pets_allowed_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smoking_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='typical_age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
