# Generated by Django 5.2.5 on 2025-09-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_sitesettings_acc_accessible_wc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='acc_hearing_loop',
            new_name='awareness_team_available',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='awareness_contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='awareness_contact_hours',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='awareness_contact_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='awareness_contact_phone',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='awareness_contact',
            field=models.CharField(blank=True, help_text='Phone, email, URL, or a short instruction (free text).', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lgbtq_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='minors_policy_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
