# Generated by Django 5.2.5 on 2025-09-03 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_rename_acc_hearing_loop_sitesettings_awareness_team_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibilityrule',
            name='key',
            field=models.SlugField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.\\-:]+$', 'Key may contain letters, numbers, underscores, hyphens, dots, or colons.')]),
        ),
    ]
