# Generated by Django 5.2.5 on 2025-09-03 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_visibilityrule_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibilityrule',
            name='key',
            field=models.CharField(db_index=True, max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.\\-:]+$', 'Key may contain letters, numbers, underscores, hyphens, dots, or colons.')]),
        ),
    ]
