# Generated by Django 5.2.5 on 2025-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_visibilityrule_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='publish_opening_times',
            field=models.BooleanField(default=False, help_text='If checked, opening times will be rendered on public pages.', verbose_name='Show opening times on public pages'),
        ),
    ]
