# Generated by Django 5.2.5 on 2025-09-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_seed_demo_non_alcoholic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alcohol by volume (%)', max_digits=5, null=True),
        ),
    ]
