# Generated by Django 5.2.5 on 2025-09-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_demo_item'),
        ('menu', '0004_alter_itemvariant_abv'),
    ]

    operations = [
    ]
