# Generated by Django 5.2.5 on 2025-09-03 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_merge_0003_demo_item_0004_alter_itemvariant_abv'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allergens_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('drink', 'Drink'), ('food', 'Food')], max_length=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid “slug” (letters, numbers, underscores, or hyphens).', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid “slug” (letters, numbers, underscores, or hyphens).', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='label',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('allowed_units', models.ManyToManyField(blank=True, to='menu.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='unit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.unitgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_group_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.unitgroup'),
        ),
    ]
