# Generated by Django 5.2.5 on 2025-09-15 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comms', '0001_initial'),
        ('users', '0004_alter_fieldpolicy_options_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('autosaved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('editing', 'Editing'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('discarded', 'Discarded')], default='editing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='label',
            name='comms_label_unique',
        ),
        migrations.RemoveConstraint(
            model_name='readreceipt',
            name='comms_read_unique',
        ),
        migrations.RemoveConstraint(
            model_name='userthreadstate',
            name='comms_user_thread_state_unique',
        ),
        migrations.AlterField(
            model_name='readreceipt',
            name='read_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('account', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='readreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userthreadstate',
            unique_together={('thread', 'user')},
        ),
        migrations.AddIndex(
            model_name='readreceipt',
            index=models.Index(fields=['user', '-read_at'], name='comms_readr_user_id_b31cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='userthreadstate',
            index=models.Index(fields=['user', 'archived', '-last_read_at'], name='comms_usert_user_id_e226f6_idx'),
        ),
        migrations.AddIndex(
            model_name='userthreadstate',
            index=models.Index(fields=['user', 'starred', '-last_read_at'], name='comms_usert_user_id_3528da_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiencelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('badge__isnull', False), ('group__isnull', True), ('user__isnull', True)), models.Q(('badge__isnull', True), ('group__isnull', False), ('user__isnull', True)), models.Q(('badge__isnull', True), ('group__isnull', True), ('user__isnull', False)), _connector='OR'), name='comms_audience_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='internaltarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('badge__isnull', False), ('group__isnull', True), ('user__isnull', True)), models.Q(('badge__isnull', True), ('group__isnull', False), ('user__isnull', True)), models.Q(('badge__isnull', True), ('group__isnull', True), ('user__isnull', False)), _connector='OR'), name='comms_internal_target_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='internaltarget',
            constraint=models.UniqueConstraint(fields=('thread', 'badge', 'group', 'user'), name='comms_internal_target_unique_member'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', True), ('direction', 'internal')), ('direction__in', ['inbound', 'outbound']), _connector='OR'), name='comms_message_direction_account_consistency'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('type', 'email')), models.Q(('account__isnull', True), ('type', 'internal')), _connector='OR'), name='comms_thread_type_account_consistency'),
        ),
        migrations.AddField(
            model_name='draft',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comms.mailaccount'),
        ),
        migrations.AddField(
            model_name='draft',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draft',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comms.messagethread'),
        ),
    ]
