# Generated by Django 5.2.5 on 2025-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_draft_remove_label_comms_label_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='attachments_meta',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='bcc_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='cc_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='to_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
