# Generated by Django 5.2.5 on 2025-09-11 14:41

import app.assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique identifier for embedding; can be renamed.', max_length=200, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='public', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.collection')),
            ],
            options={
                'ordering': ['parent__id', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique within collection.', max_length=255)),
                ('visibility', models.CharField(choices=[('inherit', 'Inherit from collection'), ('public', 'Public'), ('internal', 'Internal')], default='inherit', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=app.assets.models.asset_upload_to)),
                ('url', models.URLField(blank=True, help_text='For external links/embeds', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('doc', 'Document'), ('archive', 'Archive'), ('link', 'Link'), ('other', 'Other')], default='other', max_length=20)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.collection')),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='assets.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('collection', 'slug')},
            },
        ),
    ]
