# Generated by Django 5.2.5 on 2025-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='visibility',
        ),
        migrations.AddField(
            model_name='asset',
            name='appears_on',
            field=models.CharField(blank=True, help_text='Auto-filled by editor; informative only.', max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='If enabled, forces Internal visibility.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='text_content',
            field=models.TextField(blank=True, help_text='Plain text / note / credentials (handle with care)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='asset_collections', to='auth.group'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='collections', to='assets.tag'),
        ),
        migrations.AddField(
            model_name='collection',
            name='visibility_mode',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal (staff)'), ('groups', 'Groups')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('doc', 'Document'), ('archive', 'Archive'), ('link', 'Link'), ('note', 'Text/Note'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique within collection. Leave blank to auto-slug.', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, help_text='External link or embed URL', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for auto-slug.', max_length=200, unique=True),
        ),
    ]
