# Generated by Django 5.2.5 on 2025-09-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_collection_visibility_asset_appears_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_secret',
        ),
        migrations.AlterField(
            model_name='asset',
            name='text_content',
            field=models.TextField(blank=True, help_text='Plain text / note / credentials'),
        ),
    ]
