# Generated by Django 5.2.5 on 2025-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_is_secret_alter_asset_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('doc', 'Document'), ('archive', 'Archive'), ('link', 'Link'), ('note', 'Text/Note'), ('font', 'Font'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
