# Generated by Django 5.2.6 on 2025-10-01 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Optional hex color (without #) used for UI accents.', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Shown publicly; defaults to the linked band's name.", max_length=200)),
                ('performer_type', models.CharField(blank=True, help_text='Optional override (DJ set, acoustic, support, etc.).', max_length=16)),
                ('slot_starts_at', models.DateTimeField(blank=True, null=True)),
                ('slot_ends_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'slot_starts_at', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='events/hero/')),
                ('teaser', models.CharField(blank=True, help_text='Short summary for cards, social previews, SEO descriptions.', max_length=280)),
                ('description_public', models.TextField(blank=True, help_text='Markdown or HTML rendered on the public site.')),
                ('description_internal', models.TextField(blank=True, help_text='Staff-only notes (door team briefings, settlement notes, etc.)')),
                ('doors_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('curfew_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('ticket_price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ticket_price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('requires_shifts', models.BooleanField(default=False, help_text='If checked, event will appear in the shift planner.')),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=255)),
                ('venue_postal_code', models.CharField(blank=True, max_length=32)),
                ('venue_city', models.CharField(blank=True, max_length=120)),
                ('venue_country', models.CharField(blank=True, max_length=120)),
                ('venue_timezone', models.CharField(blank=True, max_length=64)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('visibility_key', models.CharField(blank=True, help_text='Visibility rule key (managed via the setup visibility cogs).', max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', 'title'],
            },
        ),
    ]
