# Generated by Django 5.2.6 on 2025-10-01 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0003_alter_band_compensation_type'),
        ('events', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shift_preset',
            field=models.ForeignKey(blank=True, help_text='Optional template used to prefill shifts when the event is saved.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftpreset'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Pick all that apply (used for filtering and SEO markup).', related_name='events', to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventperformer',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_slots', to='bands.band'),
        ),
        migrations.AddField(
            model_name='eventperformer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='events.event'),
        ),
    ]
