# Generated by Django 5.2.6 on 2025-10-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('shifts', '0002_shifttemplate_shift_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='standard_shifts',
            field=models.ManyToManyField(blank=True, help_text='Select standard shifts (door, bar, etc.) to generate for this event.', related_name='events', to='shifts.shifttemplate'),
        ),
    ]
