# Generated by Django 5.2.6 on 2025-10-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_standard_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue_timezone',
        ),
    ]
