# Generated by Django 5.2.6 on 2025-10-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_venue_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='shift_preset',
        ),
    ]
