# Generated by Django 5.2.6 on 2025-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_shift_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific day of the month (1-31) for date-based recurrences.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_frequency',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('weekly', 'Weekly'), ('biweekly', 'Every other week'), ('monthly_date', 'Monthly (specific date)'), ('monthly_weekday', 'Monthly (weekday, e.g. 1st Thursday)')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_next_start_at',
            field=models.DateTimeField(blank=True, help_text='Optional next scheduled start when managing recurring series.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_week_of_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], help_text='Which week (1st, 2nd, etc.) of the month for weekday-based recurrences.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekday used for recurring patterns.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
