# Generated by Django 5.2.6 on 2025-11-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0006_event_event_type_event_recurrence_day_of_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="recurrence_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this event overrides a single occurrence of the parent recurrence.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence_overrides",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_parent_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Original start datetime for the overridden occurrence.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HolidayWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "applies_to_internal",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, internal events will still be scheduled.",
                    ),
                ),
                (
                    "applies_to_public",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, public events will still be scheduled.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holiday_windows_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holiday_windows_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRecurrenceException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurrence_start", models.DateTimeField()),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("skip", "Skip occurrence"),
                            ("override", "Override occurrence"),
                            ("holiday", "Holiday blackout"),
                        ],
                        default="skip",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_exceptions",
                        to="events.event",
                    ),
                ),
                (
                    "override_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_exception",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurrence_start"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventrecurrenceexception",
            constraint=models.UniqueConstraint(
                fields=("event", "occurrence_start"),
                name="unique_event_occurrence_exception",
            ),
        ),
    ]
