# Generated by Django 5.2.5 on 2025-09-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_type', models.CharField(choices=[('band', 'Band'), ('dj', 'DJ'), ('solo', 'Solo artist')], default='band', max_length=10)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Auto-filled from name; you can edit.', max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bands/')),
                ('contact_type', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('url', 'Website/Link'), ('other', 'Other')], max_length=10)),
                ('contact_value', models.CharField(blank=True, help_text='Email, phone number, or URL.', max_length=255)),
                ('contact_notes', models.CharField(blank=True, help_text='How contact was made / extra notes.', max_length=255)),
                ('compensation_type', models.CharField(choices=[('fixed', 'Fixed fee'), ('door', 'Door deal'), ('unpaid', 'Unpaid / promo')], default='fixed', max_length=10)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Paid amount for fixed fee.', max_digits=9, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, help_text='Entry price if door deal.', max_digits=6, null=True)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payout amount they got.', max_digits=9, null=True)),
                ('comment_internal', models.TextField(blank=True, help_text='Private notes for staff (not public).')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, help_text='Optional <title> override.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description.', max_length=160)),
                ('og_image_override', models.ImageField(blank=True, null=True, upload_to='bands/og/')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('bandcamp', models.URLField(blank=True)),
                ('soundcloud', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
