# Generated by Django 5.2.5 on 2025-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='last_performed_on',
            field=models.DateField(blank=True, help_text='Date they performed at our venue.', null=True),
        ),
    ]
