# Generated by Django 5.2.5 on 2025-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_band_last_performed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='compensation_type',
            field=models.CharField(choices=[('fixed', 'Fixed fee'), ('door', 'Door deal'), ('unpaid', 'Unpaid / promo')], default='unpaid', max_length=10),
        ),
    ]
